In [ ]:
import numpy as np
print("DataSet")
data = np.genfromtxt('data.csv',delimiter=',')
data = data.astype('int32')
print(data)

DataSet
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [16 27 28 29 30]]


In [ ]:
data.dtype

dtype('int32')

In [ ]:
type(data)

numpy.ndarray

In [ ]:
data.shape

(6, 5)

In [ ]:
data.size

30

In [ ]:
data.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [16, 27, 28, 29, 30]], dtype=int32)

In [ ]:
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [16 27 28 29 30]]


In [ ]:
print(data[2:4,[0,1]])

[[11 12]
 [16 17]]


In [ ]:
print(data[2:4,0:2])

[[11 12]
 [16 17]]


In [ ]:
print(data[0:2,[3,4]])

[[ 4  5]
 [ 9 10]]


In [ ]:
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [16 27 28 29 30]]


In [ ]:
print(data[0][1:2],data[1][2:3],data[2][3:4],data[3][4:5])
print(data)
data[[0,1,2,3],[1,2,3,4]]

[2] [8] [14] [20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [16 27 28 29 30]]


array([ 2,  8, 14, 20], dtype=int32)

In [ ]:
# print 4,5,24,25,29,30
#print(data[0:1,3:],data[4:5,3:],data[5:,3:])
#print(data)
data[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int32)

In [ ]:
# Speech To Text
https://learntodroid.com/how-to-use-ibms-watson-speech-to-text-service-in-an-android-app/