In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(3, 3)

In [ ]:
a.size

9

In [ ]:
a.max()

9

In [ ]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(2, 3)

In [ ]:
#np.arange(start,stop,step)
c = np.arange(6)
print(c)
type(c)

[0 1 2 3 4 5]


numpy.ndarray

In [ ]:
#np.arange(start,stop,step)
c = np.arange(6,9)
print(c)
type(c)

[6 7 8]


numpy.ndarray

In [ ]:
#np.arange(start,stop,step)
c = np.arange(6,12,2)
print(c)
type(c)

[ 6  8 10]


numpy.ndarray

In [ ]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
d = np.ones((2,2))
print(d)

[[1. 1.]
 [1. 1.]]


In [ ]:
rm = np.random.random((2,2))
print(rm)

[[0.6859479  0.93122246]
 [0.59971531 0.23589029]]
