In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#Create a 0-D array with value 42
arr = np.array(42)
print(arr)

42


In [ ]:
#Create a 1-D array containing the values 1,2,3,4,5:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2])

1
2
3


In [ ]:
x = np.array([[1,2,3,4],[4,5,6,7],[1,2,3,4],[4,5,6,7]])
print(x)

[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]
 [4 5 6 7]]


In [ ]:
import numpy as np

x = np.array([[1,2,3,4],[4,5,6,7],[1,2,3,4],[4,5,6,7]])
print(x)

print(x[:,[0,3]])

[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]
 [4 5 6 7]]
[[1 4]
 [4 7]
 [1 4]
 [4 7]]


In [ ]:
x = np.array([[1,2,3,4],[4,5,6,7],[1,2,3,4],[8,5,6,9]])
print(x)

print(x[-1:,0])
print(x[3:,3])

[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]
 [8 5 6 9]]
[8]
[9]


In [ ]:
x = np.array([[1,2,3,4],[4,5,6,7],[1,2,3,4],[8,5,6,9]])
print(x)


print(x[-4:,3])

[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]
 [8 5 6 9]]
[4 7 4 9]
